### ISSUE TITLE
Circuit to FSM Algorithm (Reverse)

### ISSUE THREAD

**Issue by BookGin** [DSDL2016/FwdRevDesign#2]

**Comment by CTinRay** [comment]
這邊如何了呀 :question:

**Comment by zkelly3** [comment]
commit 30728d9b726c1f2f42803cf8cee6a94e6b9c6bc6

**Comment by CTinRay** [comment]
突然想到
所以你生出來的fsm
狀態的名稱會剛好就是 flip-flop 的狀態嗎？

像是如果在某個狀態的兩個D flip-flop分別儲存著0和1
那麼這個狀態的名稱會是"01"嗎？

**Comment by CTinRay** [comment]
然後如果稍微測試過沒有問題
把全域變數修掉後（詳情可以問 @BookGin )
就可以送 pull request 囉

**PS.**
即使

``` js
Algorithm.forward = function(){
// ...
}
```

是一個函式
但是還是可以

``` js
Algorithm.forward.blah = 'ah';
```

像這樣亂加 property 喔

**Comment by CTinRay** [comment]
Gate 不是一個參數
是宣告在某個地方的全域變數
所以不用放在參數喔...
（merge的時候沒看到）

**Comment by CTinRay** [comment]
There is another issue https://github.com/DSDL2016/FwdRevDesign/issues/22.

**Comment by BookGin** [comment]
#22 already closed.
