### ISSUE TITLE
Forward: Implement With Different FF

### ISSUE THREAD

**Issue by BookGin** [DSDL2016/FwdRevDesign#20]
Refer to #6 

> Unfortunately, the situation now becomes more complicated :scream:
> 
> According to the official test case, we have to support different FF implementation in a fsm.
> Thus in Algorithm.forward(), I may add a parameter to specify FF implementation.

[test case](http://graphics.csie.ntu.edu.tw/%7Eming/courses/dsd2016/material/forward_reverse_testcase.docx)

**Comment by BookGin** [comment]
By adding a _NOT_ gate, it's very easy to implement D, JK, SR flip-flops.
However, the T flip-flop seems not so easy.......

Any ideas?

**Comment by CTinRay** [comment]
```

    +--------------------------+
    |                          |
    |       +------------------+-----+
    |       |                  |     |
    |       |    +----------+  |     |
    |      \|/   |          |  |     |
 ---+-------X----+   T FF   +--+-----+--
    |      / \   |          |  |
    |      xor   +----------+  |
    |                          |
    |                          |
    |                          |
    +--------------------------+

```

這樣就跟 D Flip-Flop 一樣了吧？

**Comment by y3nr1ng** [comment]
D FF with its D input XORed the Q output will yield a T FF.

**Comment by BookGin** [comment]
@CTinRay @liuyenting 
I sincerely appreciate your suggestion!
I'll implement this one.

**Comment by y3nr1ng** [comment]
T FF added, case closed?

**Comment by CTinRay** [comment]
No, it is two issues.

**Comment by BookGin** [comment]
Done.
I've implemented T FF.
