### ISSUE TITLE
Algorithm.reverse 和 gate.js 在 spec 上有出入

### ISSUE THREAD

**Issue by CTinRay** [DSDL2016/FwdRevDesign#22]
@liuyenting  @zkelly3 你們可能需要一點交流
好像大家對 spec 的認知有點出入...

你們加油吧......... :astonished: 

反正至少要讓reverse在跑的時候不會噴error

**Comment by CTinRay** [comment]
嘿 這個要處理呀
不然不會動喔

**Comment by y3nr1ng** [comment]
(浮)

**Comment by zkelly3** [comment]
昨天初步看猜是因為真值表不是一維以及Q不是在最後面
(Ex. 應該是RSQ={000, 001, 010,...})

如 #8

**Comment by zkelly3** [comment]
@CTinRay 請問能夠麻煩幫忙測試testGate的branch嗎:P

**Comment by CTinRay** [comment]
你可以先 merge/rebase master 到你的 branch
然後理論上就要可以動了（吧）

**Comment by CTinRay** [comment]
@zkelly3 已經解決這部分的問題了嗎？

**Comment by CTinRay** [comment]
看起來沒事了
