### ISSUE TITLE
forward() Return More Than 2 Input Ports of OR, AND Gates

### ISSUE THREAD

**Issue by BookGin** [DSDL2016/FwdRevDesign#26]
In `Algorithm.forward()`, the return schematic contains gates with more than 2 input ports.
Unfortunately, however, this project doesn't support dynamic input ports.

My solution is to connect input ports with _2-input-OR_ only. Any ideas?

**Comment by y3nr1ng** [comment]
Can you elaborate about the type of multi-input gate please? If they are just primitive gates, such as AND, OR, XOR, you shall simply concat them.

**Comment by BookGin** [comment]
#30 PR merged.
