### ISSUE TITLE
FSM to Circuit Algorithm (Forward) 

### ISSUE THREAD

**Issue by BookGin** [DSDL2016/FwdRevDesign#3]
> 會需要針對只用某種正反器的狀況

**Comment by CTinRay** [comment]
之前忘記了
會需要針對只用某種正反器的狀況

**Comment by CTinRay** [comment]
問一下...
為什麼會有一個 html 檔在 fsm2circuit 的 branch?

**Comment by BookGin** [comment]
@CTinRay 
for testing

**Comment by CTinRay** [comment]
> 會需要針對只用某種正反器的狀況

@BookGin 你有做這個嗎？
剛剛發現 spec 裡好像沒有要求？

**Comment by BookGin** [comment]
@CTinRay 
I implement them with D flip-flop only.
`type: "dff"`

**Comment by CTinRay** [comment]
According to the [test case](http://graphics.csie.ntu.edu.tw/%7Eming/courses/dsd2016/material/forward_reverse_testcase.docx), converting fsm to schematic which consists of JK flip-flop is required.

**Comment by CTinRay** [comment]
So another argument will be pass to `Algorithm.forward`.
The argument is an object which may be like

``` js
{
    ff: "D", // or "JK"
    named: "true"
}
```

where 
- ff: type of flip-flop to use. Acceptable option includes "D", "JK" (at least?).
- named: describe whether the algorithm should take the name of state into consideration.
  - If `true`, then the name of each state is meaningful string constituted with '0' and '1'. But I can't guarantee the length (entered by user) is as your expectation (like `1` or `001011010011`).
  - If `false`, then the algorithm should see those state name as meaningless, even if some of them may look like a binary string.

**Note**
You can return an object

``` js
{
    error: "Ah...something goes wrong"
}
```

If something goes wrong.

**Comment by BookGin** [comment]
@CTinRay 
- OK. I 'll implement with D or JK filp-flops.
- I can treat the name of each state as meangingless, regardless of its form. Therefore, there is no need to pass boolean parameter `name`.

**Comment by CTinRay** [comment]
According to the test cases, both of them provide flip-flop state as part of state diagram.
Therefore, you may always need to take the state name into consideration.
By the way, it seems that start state is not required. "00" may be the start state.

So `named` option is not required.

**Comment by CTinRay** [comment]
@BookGin 

Not sure where is the problem yet.

![](https://cloud.githubusercontent.com/assets/10608036/15918419/328f4f9a-2e39-11e6-9270-d272d6bfa445.png)

code is on branch `gui-enhance`.

**Comment by BookGin** [comment]
@CTinRay 
My `index.html` displays nothing. The console js error message is `ReferenceError: $ is not defined`.

As I can't run the `index.html` to perform test, can you show the parameter `fsm` you passed into  `Algorithm.forward()`?

**Comment by CTinRay** [comment]
Please try run `bower install` again.
If the problem is not solved, remove bower_components and try again.

**Comment by BookGin** [comment]
@CTinRay 
Not very sure if this is the main reason, but `fsm` doesn't follow #6 spec.
- Output bit variable is named **out** instead of `output`
- Also, its type is **string**, not `number`.

**Comment by CTinRay** [comment]
ok, my fault.
I will fix them

**Comment by BookGin** [comment]
If ther are new bugs, please create a new issue.
