### ISSUE TITLE
Type Error in Reverse

### ISSUE THREAD

**Issue by y3nr1ng** [DSDL2016/FwdRevDesign#37]
<img width="1440" alt="screen shot 2016-06-16 at 11 50 54" src="https://cloud.githubusercontent.com/assets/2089799/16104989/a8a33938-33b8-11e6-90da-89ce8866b2fa.png">

**Comment by zkelly3** [comment]
or本來就不是sequential gate 不能這樣接有環會壞掉

**Comment by y3nr1ng** [comment]
所以這是 feature...
