### ISSUE TITLE
畫 gate

### ISSUE THREAD

**Issue by CTinRay** [DSDL2016/FwdRevDesign#5]
把 gate 的圖畫完

好像還缺 or and xor nand 之類的

如果可以的話用向量圖畫
但是暫時先輸出成 100 x 100 的 png （原檔要留下來或一起推上來
我還沒有把 css 設定固定寬度，所以超過會爛掉
然後像 or gate 這種有腳伸出來的
y 座標要能對到GUI上接線的圓點
(像是[這個](http://www.jointjs.com/demos/logic)的gate其實都是方形的圖)

**Comment by y3nr1ng** [comment]
- 2 port: 25px padding, 50px separations
- width and height: 100px
- internal wire length: not limited

**Comment by y3nr1ng** [comment]
Check PR #17 for the result.
