### ISSUE TITLE
FSM And FF Type Spec

### ISSUE THREAD

**Issue by BookGin** [DSDL2016/FwdRevDesign#6]
還是先定一下 FSM 的格式好了，方便實做：

``` js
let fsm = {
 // 'state name (binary)' : [ {nextStateWhenInput0, output}, {nextStateWhenInput1, output}] 
    '00': [{next: '00', out: '0'}, {next: '01', out: '0'}],
    '01': [{next: '00', out: '0'}, {next: '10', out: '0'}],
    '10': [{next: '00', out: '0'}, {next: '11', out: '0'}],
    '11': [{next: '00', out: '0'}, {next: '01', out: '1'}]
};
```

另外要注意 javascript 對於 fsm 物件而言，**不保證 key 的順序是 00 01 10 11**

``` js
/* bitwise to state name in binary, where 
* d:D-ff, 
* j:JK-ff, 
* t:T-ff, 
* s:SR-ff 
*/
let ffType = "dtjd";
```

**Comment by CTinRay** [comment]
現在才想到
好像會有一個 start state 後

**Comment by CTinRay** [comment]
然後你應該知道
到時候餵給你的狀態圖
狀態的名稱很可能會是沒有意義的喔

**Comment by BookGin** [comment]
沒差在寫一個func生就好了 很快

**Comment by BookGin** [comment]
Unfortunately, the situation now becomes more complicated :scream: 

According to the official [test case](http://graphics.csie.ntu.edu.tw/%7Eming/courses/dsd2016/material/forward_reverse_testcase.docx), we have to support different FF implementation in a _fsm_.
Thus in `Algorithm.forward()`, I may add a parameter to specify FF implementation.

**Comment by BookGin** [comment]
@CTinRay 
Can you provide valid FF names?
Current:

```
jk
rs
t
d
```

**Comment by CTinRay** [comment]
check `js/gate.js` 
yes, there are rs, jk, d, t

**Comment by BookGin** [comment]
Move to [wiki](https://github.com/DSDL2016/FwdRevDesign/wiki/FSM-And-FF-Type-Spec)
