### ISSUE TITLE
閘的描述要用 真值表 還是 函數

### ISSUE THREAD

**Issue by y3nr1ng** [DSDL2016/FwdRevDesign#8]
如題目 D: 目前是用真值表，如果是用真值表，呼叫格式請參見註解們，如果這樣不好操作的話，我們來微調真值表的樣子 ber，本來在 #1 當中被改掉的樣子，在 Q-state 不同的時候有點難描述 :(

**Comment by BookGin** [comment]
我寫的時候格式是這樣
Y = ABC + A'C' 會表示成

``` js
Y = [
"111", "0x0"
];
// expressed in the product-of-sum form
// 1: postive
// 0: negative
// x: undefined
```

所以truth table的表示法 如果能很好 parse 成這種格式的話
就太棒了

**Comment by zkelly3** [comment]
我應該會用真值表
另外之後應該會把seq的真值表都拆成兩個
這樣窮舉比較不會有跑環的問題

**Comment by CTinRay** [comment]
不過 @liuyenting 已經都寫完了？

然後 Tor 這個 branch 是不是可以刪掉了？
（ @liuyenting 要解釋一下 Tor 是什麼意思嗎？

**Comment by y3nr1ng** [comment]
是啊，真值表都寫完了怎麼了？
AND, NAND, OR, NOR, XOR, RS FF, JK FF, D FF 醬子

可以刪喔，麻煩你惹。Tor 是 Gate 的意思。

**Comment by CTinRay** [comment]
@zkelly3 跑環是指？

**Comment by zkelly3** [comment]
就是要拓樸排序 但sequential的邏輯閘不拆掉都會是環狀的沒辦法計算順序

**Comment by CTinRay** [comment]
拓樸排序電路嗎？
那跟 seq 的真值表有什麼關係？

然後 @BookGin 和 @zkelly3 要不要確認一下 @liuyenting 寫的 gate.js 你們用起來會不會不好用

**Comment by zkelly3** [comment]
要拆成
QRS -> Q^t+1
Q -> Q, -Q
這樣就要變兩張表吧(?)

然後在寫我那邊的時候希望seq的有nState計算他有幾個internal state
而且維度那麼多在爆搜的時候會比較麻煩

像是[0, 1, 0]
把 truthTable[0][1][0] 的值拿出來
跟把 truthTable[010b] 的值拿出來
的差別

另外希望gate再多input跟output
要不然像or gate明明沒有output結果要直接看id:2很困擾

**Comment by y3nr1ng** [comment]
GG 有點不太懂 @zkelly3 可以給個範例嗎？讓我可以照著把其它的一併改掉

**Comment by zkelly3** [comment]
@liuyenting 要給什麼的範例(?

**Comment by y3nr1ng** [comment]
就，針對八樓的說明，能否給個閘的定義範例，像是給 DFF 這種比較簡單的定義。然後我再從這個定義去把 RS JK 跟其它 non-sequential 的元件照著改好。

**Comment by zkelly3** [comment]
@liuyenting 

RS flip-flop
    RSQ -> [Q^t+1]
    Q -> [Q, -Q]

```
truthTable: {
    first: [ // RSQ -> [Q^t+1]
        [0], // 000
        [1], // 001
        [1], // 010
        [1], // 011
        [0], // 100
        [0], // 101
        [undefined], //110
        [undefined]  //111
    ],
    second: [ // Q -> [Q, -Q]
        [0, 1],//0
        [1, 0] //1
    ]
}
```

希望sequential的truthtable都像這樣有兩張

**Comment by CTinRay** [comment]
所以這邊狀況是？

沒問題的話 @liuyenting  就把它關囉

**Comment by y3nr1ng** [comment]
請參見 #22
